apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
  namespace: cybereason
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
      - name: counter-service
        image: public.ecr.aws/h3y5e4s1/cybereason_exam/counter-service:1.0
        imagePullPolicy: Always
        env:
        - name: BASE_DIR
          value: "/"
        ports:
        - containerPort: 443
---

apiVersion: v1
kind: Service
metadata:
  name: counter-service-svc
  namespace: cybereason
spec:
  selector:
    app: counter-service
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP